version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  website:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"